version: "3.8"
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://admin:password123@mongo:27017/mydatabase?authSource=admin

  mongo:
    image: mongo
    container_name: my-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./.env.local

volumes:
  mongo-data:
